consolidated workflow back to single file and trigger deploy after builds are successful.

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -1,4 +1,4 @@
-name: CI
+name: CI-CD
 
 on:
   workflow_dispatch:
@@ -376,3 +376,42 @@ jobs:
               }
             }
 
+  trigger_gitlab_pipeline:
+      runs-on: ubuntu-latest
+      if: ${{ github.repository =='Lumerin-protocol/Morpheus-Lumerin-Node' && (github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/stg' || github.ref == 'refs/heads/dev')) }}
+      needs:
+        - Ubuntu-22-x64
+        - macOS-13-x64
+        - macOS-14-arm64
+        - Windows-avx2-x64
+      steps:
+        - name: Determine GitLab Target Branch
+          id: set_target_branch
+          run: |
+            if [ "${{ github.ref_name }}" == "dev" ]; then
+              echo "gitlab_branch=dev" >> $GITHUB_ENV
+            elif [ "${{ github.ref_name }}" == "stg" ]; then
+              echo "gitlab_branch=stg" >> $GITHUB_ENV
+            elif [ "${{ github.ref_name }}" == "main" ]; then
+              echo "gitlab_branch=main" >> $GITHUB_ENV
+            else
+              echo "This branch is not configured to trigger GitLab pipelines."
+              exit 1
+            fi
+
+        - name: Trigger GitLab Pipeline
+          run: |
+            echo "Triggering GitLab pipeline for branch ${{ env.gitlab_branch }}"
+            response=$(curl --write-out "%{http_code}" --silent --output /dev/null \
+              --request POST \
+              --url "${{ secrets.GITLAB_TRIGGER_URL }}" \
+              --form "token=${{ secrets.GITLAB_TRIGGER_TOKEN }}" \
+              --form "ref=${{ env.gitlab_branch }}" \
+              --form "variables[SOURCE_REPO]=${{ github.repository }}" \
+              --form "variables[SOURCE_BRANCH]=${{ github.ref_name }}")
+
+            if [ "$response" -ne 200 ]; then
+              echo "Failed to trigger GitLab pipeline. HTTP status: $response"
+              exit 1
+            fi
+          
