fine tuned gitlab-trigger

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -28,6 +28,53 @@ defaults:
     shell: bash
     
 jobs:
+  trigger_gitlab:
+    runs-on: ubuntu-latest
+    if: ${{ github.repository != 'MorpheusAIs/Morpheus-Lumerin-Node' && (github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/test' || github.ref == 'refs/heads/dev' )) }}
+
+    steps:
+      - name: Generate Tag Name
+        uses: ./.github/actions/gen_tag_name
+
+      - name: Determine GitLab Target Branch
+        id: set_target_branch
+        run: |
+          if [ "${{ github.ref_name }}" == "dev" ]; then
+            echo "gitlab_branch=dev" >> $GITHUB_ENV
+          elif [ "${{ github.ref_name }}" == "test" ]; then
+            echo "gitlab_branch=stg" >> $GITHUB_ENV
+          elif [ "${{ github.ref_name }}" == "main" ]; then
+            echo "gitlab_branch=main" >> $GITHUB_ENV
+          else
+            echo "This branch is not configured to trigger GitLab pipelines."
+            exit 1
+          fi
+
+      - name: Trigger GitLab Pipeline
+        run: |
+          echo "Triggering GitLab pipeline for branch ${{ env.gitlab_branch }} with tag ${{ env.TAG_NAME }}"
+      
+          # Send request to GitLab
+          response=$(curl --write-out "\n%{http_code}" --silent --output /tmp/gitlab_response \
+            --request POST \
+            --url "${{ secrets.GITLAB_TRIGGER_URL }}" \
+            --form "token=${{ secrets.GITLAB_TRIGGER_TOKEN }}" \
+            --form "ref=${{ env.gitlab_branch }}" \
+            --form "variables[SOURCE_REPO]=${{ github.repository }}" \
+            --form "variables[SOURCE_BRANCH]=${{ github.ref_name }}" \
+            --form "variables[GITHUB_TAG]=${{ env.TAG_NAME }}")
+          
+          # Extract status code and response body
+          status_code=$(tail -n 1 /tmp/gitlab_response)
+          response_body=$(head -n -1 /tmp/gitlab_response)
+      
+          # Log and handle response
+          if [[ "$status_code" != 2* ]]; then
+            echo "Gitlab pipeline FAILED. HTTP status: $status_code"
+            echo "GitLab Response: $response_body"
+            exit 1
+          fi
+          echo "GitLab pipeline triggered successfully. HTTP status: $status_code"
   Ubuntu-22-x64:
     if: ${{ github.repository != 'MorpheusAIs/Morpheus-Lumerin-Node' }}
     runs-on: ubuntu-22.04
@@ -378,43 +425,4 @@ jobs:
                 });
               }
             }
-
-  trigger_gitlab_pipeline:
-      runs-on: ubuntu-latest
-      if: ${{ github.repository != 'MorpheusAIs/Morpheus-Lumerin-Node' && (github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/test' || github.ref == 'refs/heads/dev' )) }}
-      needs:
-        - Ubuntu-22-x64
-        - macOS-13-x64
-        - macOS-14-arm64
-        - Windows-avx2-x64
-      steps:
-        - name: Determine GitLab Target Branch
-          id: set_target_branch
-          run: |
-            if [ "${{ github.ref_name }}" == "dev" ]; then
-              echo "gitlab_branch=dev" >> $GITHUB_ENV
-            elif [ "${{ github.ref_name }}" == "test" ]; then
-              echo "gitlab_branch=stg" >> $GITHUB_ENV
-            elif [ "${{ github.ref_name }}" == "main" ]; then
-              echo "gitlab_branch=main" >> $GITHUB_ENV
-            else
-              echo "This branch is not configured to trigger GitLab pipelines."
-              exit 1
-            fi
-
-        - name: Trigger GitLab Pipeline
-          run: |
-            echo "Triggering GitLab pipeline for branch ${{ env.gitlab_branch }}"
-            response=$(curl --write-out "%{http_code}" --silent --output /dev/null \
-              --request POST \
-              --url "${{ secrets.GITLAB_TRIGGER_URL }}" \
-              --form "token=${{ secrets.GITLAB_TRIGGER_TOKEN }}" \
-              --form "ref=${{ env.gitlab_branch }}" \
-              --form "variables[SOURCE_REPO]=${{ github.repository }}" \
-              --form "variables[SOURCE_BRANCH]=${{ github.ref_name }}")
-
-            if [[ "$response" != 2* ]]; then
-              echo "Failed to trigger GitLab pipeline. HTTP status: $response"
-              exit 1
-            fi
-          
+         
