add Ubuntu and Windows ARM64 package builds for proxy, cli and ui..prep for matrix builds

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -84,7 +84,7 @@ jobs:
         shell: bash
         run: |
           IMAGE_NAME="ghcr.io/lumerin-protocol/morpheus-lumerin-node"
-          VMAJ_NEW=3
+          VMAJ_NEW=4
           VMIN_NEW=0
           VPAT_NEW=0
           set +o pipefail
@@ -246,34 +246,47 @@ jobs:
       - name: Build executables for all platforms
         run: |
           cd proxy-router
-          # Linux
-          TAG_NAME=${{ needs.Generate-Tag.outputs.tag_name }} GOOS=linux GOARCH=amd64 OUTPUT=proxy-router-linux-amd64 ./build.sh || (echo "❌ Failed to build Linux executable" && exit 1)
+          # Linux X64
+          TAG_NAME=${{ needs.Generate-Tag.outputs.tag_name }} GOOS=linux GOARCH=amd64 OUTPUT=proxy-router-linux-amd64 ./build.sh || (echo "❌ Failed to build Linux X64 executable" && exit 1)
           mv proxy-router proxy-router-linux-amd64
+          # Linux ARM64
+          TAG_NAME=${{ needs.Generate-Tag.outputs.tag_name }} GOOS=linux GOARCH=arm64 OUTPUT=proxy-router-linux-arm64 ./build.sh || (echo "❌ Failed to build Linux ARM64 executable" && exit 1)
+          mv proxy-router proxy-router-linux-arm64
           # macOS Intel
-          TAG_NAME=${{ needs.Generate-Tag.outputs.tag_name }} GOOS=darwin GOARCH=amd64 OUTPUT=proxy-router-darwin-amd64 ./build.sh || (echo "❌ Failed to build macOS Intel executable" && exit 1)
+          TAG_NAME=${{ needs.Generate-Tag.outputs.tag_name }} GOOS=darwin GOARCH=amd64 OUTPUT=proxy-router-darwin-amd64 ./build.sh || (echo "❌ Failed to build macOS X64 executable" && exit 1)
           mv proxy-router proxy-router-darwin-amd64
           # macOS ARM (Apple Silicon)
-          TAG_NAME=${{ needs.Generate-Tag.outputs.tag_name }} GOOS=darwin GOARCH=arm64 ./build.sh || (echo "❌ Failed to build macOS ARM executable" && exit 1)
+          TAG_NAME=${{ needs.Generate-Tag.outputs.tag_name }} GOOS=darwin GOARCH=arm64 OUTPUT=proxy-router-darwin-arm64 ./build.sh || (echo "❌ Failed to build macOS ARM64 executable" && exit 1)
           mv proxy-router proxy-router-darwin-arm64
-          # Windows
-          TAG_NAME=${{ needs.Generate-Tag.outputs.tag_name }} GOOS=windows GOARCH=amd64 ./build.sh || (echo "❌ Failed to build Windows executable" && exit 1)
+          # Windows X64
+          TAG_NAME=${{ needs.Generate-Tag.outputs.tag_name }} GOOS=windows GOARCH=amd64 OUTPUT=proxy-router-windows-amd64.exe ./build.sh || (echo "❌ Failed to build Windows X64 executable" && exit 1)
           mv proxy-router proxy-router-windows-amd64.exe
+          # Windows ARM64
+          TAG_NAME=${{ needs.Generate-Tag.outputs.tag_name }} GOOS=windows GOARCH=arm64 OUTPUT=proxy-router-windows-arm64.exe ./build.sh || (echo "❌ Failed to build Windows ARM64 executable" && exit 1)
+          mv proxy-router proxy-router-windows-arm64.exe
           echo "✅ Built executables for all platforms"
 
       - name: Build CLI Executables
         run: |
           cd cli
-          GOOS=linux GOARCH=amd64 make build || (echo "❌ Failed to build Linux executable" && exit 1)
+          # Linux X64
+          GOOS=linux GOARCH=amd64 make build || (echo "❌ Failed to build Linux X64 executable" && exit 1)
           mv mor-cli mor-cli-linux-amd64
+          # Linux ARM64
+          GOOS=linux GOARCH=arm64 make build || (echo "❌ Failed to build Linux ARM64 executable" && exit 1)
+          mv mor-cli mor-cli-linux-arm64
           # macOS Intel
-          GOOS=darwin GOARCH=amd64 make build || (echo "❌ Failed to build macOS Intel executable" && exit 1)
+          GOOS=darwin GOARCH=amd64 make build || (echo "❌ Failed to build macOS X64 executable" && exit 1)
           mv mor-cli mor-cli-darwin-amd64
           # macOS ARM (Apple Silicon)
-          GOOS=darwin GOARCH=arm64 make build || (echo "❌ Failed to build macOS ARM executable" && exit 1)
+          GOOS=darwin GOARCH=arm64 make build || (echo "❌ Failed to build macOS ARM64 executable" && exit 1)
           mv mor-cli mor-cli-darwin-arm64
-          # Windows
-          GOOS=windows GOARCH=amd64 make build || (echo "❌ Failed to build Windows executable" && exit 1)
+          # Windows X64
+          GOOS=windows GOARCH=amd64 make build || (echo "❌ Failed to build Windows X64 executable" && exit 1)
           mv mor-cli mor-cli-windows-amd64.exe
+          # Windows ARM64
+          GOOS=windows GOARCH=arm64 make build || (echo "❌ Failed to build Windows ARM64 executable" && exit 1)
+          mv mor-cli mor-cli-windows-arm64.exe
           echo "✅ Built executables for all platforms"
 
       - name: Upload artifacts
@@ -282,13 +295,17 @@ jobs:
           name: proxy-router-executables
           path: |
             proxy-router/proxy-router-linux-amd64
+            proxy-router/proxy-router-linux-arm64
             proxy-router/proxy-router-darwin-amd64
             proxy-router/proxy-router-darwin-arm64
             proxy-router/proxy-router-windows-amd64.exe
+            proxy-router/proxy-router-windows-arm64.exe
             cli/mor-cli-linux-amd64
+            cli/mor-cli-linux-arm64
             cli/mor-cli-darwin-amd64
             cli/mor-cli-darwin-arm64
             cli/mor-cli-windows-amd64.exe
+            cli/mor-cli-windows-arm64.exe
 
   GitLab-Deploy-ProxyRouter:
     name: Deploy ProxyRouterto GitLab
@@ -394,13 +411,15 @@ jobs:
 
       - name: Build
         id: build
+        env:
+          ARCH: arm64
         run: |
           FULLTAG=${{ needs.Generate-Tag.outputs.vfull }}
           cd ./ui-desktop
           echo "Injecting version $FULLTAG into package.json"
           sed -i "" "s/\"version\": \".*\"/\"version\": \"$FULLTAG\"/" package.json
           cat package.json | grep '"version"'  # Optional: Verify the change
-          yarn build:mac
+          yarn build:mac:arm64
 
       - name: Upload artifacts
         uses: actions/upload-artifact@v4
@@ -409,7 +428,7 @@ jobs:
           name: morpheus-ui-${{ needs.Generate-Tag.outputs.vfull }}-arm64-mac.dmg
 
   UI-Ubuntu-22-x64:
-    name: Build Morpheus UI Ubuntu Image
+    name: Build Morpheus UI Ubuntu x64 Image
     if: |
       github.repository != 'MorpheusAIs/Morpheus-Lumerin-Node' &&
       (
@@ -446,19 +465,78 @@ jobs:
 
       - name: Build
         id: build
+        env:
+          ARCH: x64
         run: |
           FULLTAG=${{ needs.Generate-Tag.outputs.vfull }}
           cd ./ui-desktop
           echo "Injecting version $FULLTAG into package.json"
           sed -i "s/\"version\": \".*\"/\"version\": \"$FULLTAG\"/" package.json
           cat package.json | grep '"version"'  # Optional: Verify the change
-          yarn build:linux
+          yarn build:linux:x64
 
       - name: Upload artifacts
         uses: actions/upload-artifact@v4
         with:
           path: ./ui-desktop/dist/morpheus-ui-${{ needs.Generate-Tag.outputs.vfull }}-x86_64-linux.AppImage
           name: morpheus-ui-${{ needs.Generate-Tag.outputs.vfull }}-x86_64-linux.AppImage
+
+  UI-Ubuntu-22-arm64:
+    name: Build Morpheus UI Ubuntu arm64 Image
+    if: |
+      github.repository != 'MorpheusAIs/Morpheus-Lumerin-Node' &&
+      (
+        (github.event_name == 'push' && (startsWith(github.ref, 'refs/heads/cicd/') || github.ref == 'refs/heads/main' || github.ref == 'refs/heads/test' || github.ref == 'refs/heads/dev')) ||
+        (github.event_name == 'workflow_dispatch' && (github.event.inputs.create_release == 'true' || github.event.inputs.build_all_os == 'true')) 
+      )
+    runs-on: ubuntu-22.04
+    needs:
+      - Generate-Tag
+    env:
+      SERVICE_PROXY_DOWNLOAD_URL_LINUX_ARM64: ${{ needs.Generate-Tag.outputs.artifacts_base_url }}/proxy-router-linux-arm64
+    steps:
+      - name: Enable QEMU for ARM64 builds
+        uses: docker/setup-qemu-action@v3
+
+      - name: Clone
+        id: checkout
+        uses: actions/checkout@v4
+        with:
+          fetch-depth: 0
+          fetch-tags: true
+
+      - name: Setup node
+        uses: actions/setup-node@v4
+        with:
+          node-version: 20
+          cache: "yarn"
+          cache-dependency-path: ui-desktop/yarn.lock
+
+      - name: Install dependencies
+        run: |
+          cd ./ui-desktop
+          yarn install --network-timeout 600000
+
+      - name: Copy Environment Files
+        uses: ./.github/actions/copy_env_files
+
+      - name: Build
+        id: build
+        env:
+          ARCH: arm64
+        run: |
+          FULLTAG=${{ needs.Generate-Tag.outputs.vfull }}
+          cd ./ui-desktop
+          echo "Injecting version $FULLTAG into package.json"
+          sed -i "s/\"version\": \".*\"/\"version\": \"$FULLTAG\"/" package.json
+          cat package.json | grep '"version"'  # Optional: Verify the change
+          yarn build:linux:arm64
+
+      - name: Upload artifacts
+        uses: actions/upload-artifact@v4
+        with:
+          path: ./ui-desktop/dist/morpheus-ui-${{ needs.Generate-Tag.outputs.vfull }}-arm64-linux.AppImage
+          name: morpheus-ui-${{ needs.Generate-Tag.outputs.vfull }}-arm64-linux.AppImage
 
   UI-macOS-13-x64:
     name: Build Morpheus UI macOS-x64 Image
@@ -499,13 +577,15 @@ jobs:
 
       - name: Build
         id: build
+        env:
+          ARCH: x64
         run: |
           FULLTAG=${{ needs.Generate-Tag.outputs.vfull }}
           cd ./ui-desktop
           echo "Injecting version $FULLTAG into package.json"
           sed -i "" "s/\"version\": \".*\"/\"version\": \"$FULLTAG\"/" package.json
           cat package.json | grep '"version"'  # Optional: Verify the change
-          yarn build:mac
+          yarn build:mac:x64
 
       - name: Upload artifacts
         uses: actions/upload-artifact@v4
@@ -556,13 +636,15 @@ jobs:
 
       - name: Build
         id: build
+        env:
+          ARCH: x64
         run: |
           FULLTAG=${{ needs.Generate-Tag.outputs.vfull }}       
           cd ./ui-desktop
           echo "Injecting version $FULLTAG into package.json"
           sed -i "s/\"version\": \".*\"/\"version\": \"$FULLTAG\"/" package.json
           cat package.json | grep '"version"'  # Optional: Verify the change
-          yarn build:win
+          yarn build:win:x64
 
       - name: Upload artifacts
         uses: actions/upload-artifact@v4
@@ -570,6 +652,65 @@ jobs:
           path: ./ui-desktop/dist/morpheus-ui-${{ needs.Generate-Tag.outputs.vfull }}-x64-win.exe
           name: morpheus-ui-${{ needs.Generate-Tag.outputs.vfull }}-x64-win.exe
 
+  UI-Windows-arm64:
+    name: Build Morpheus UI Windows ARM64 Image
+    if: |
+      github.repository != 'MorpheusAIs/Morpheus-Lumerin-Node' &&
+      (
+        (github.event_name == 'push' && (startsWith(github.ref, 'refs/heads/cicd') || github.ref == 'refs/heads/main' || github.ref == 'refs/heads/test' || github.ref == 'refs/heads/dev')) ||
+        (github.event_name == 'workflow_dispatch' && (github.event.inputs.create_release == 'true' || github.event.inputs.build_all_os == 'true')) 
+      )
+    runs-on: windows-latest
+    needs:
+      - Generate-Tag
+    env:
+      SERVICE_PROXY_DOWNLOAD_URL_WINDOWS_ARM64: ${{ needs.Generate-Tag.outputs.artifacts_base_url }}/proxy-router-windows-arm64.exe
+    steps:
+      - name: Clone
+        id: checkout
+        uses: actions/checkout@v4
+        with:
+          fetch-depth: 0
+          fetch-tags: true
+
+      - name: Setup node
+        uses: actions/setup-node@v4
+        with:
+          node-version: 20
+          cache: "yarn"
+          cache-dependency-path: ui-desktop/yarn.lock
+
+      - name: Install wget and sed
+        run: |
+          choco install wget --no-progress
+          choco install sed --no-progress
+
+      - name: Install dependencies
+        run: |
+          cd ./ui-desktop
+          yarn install --network-timeout 600000
+
+      - name: Copy Environment Files
+        uses: ./.github/actions/copy_env_files
+
+      - name: Build
+        id: build
+        env:
+          ARCH: arm64
+        run: |
+          FULLTAG=${{ needs.Generate-Tag.outputs.vfull }}
+          cd ./ui-desktop
+          echo "Injecting version $FULLTAG into package.json"
+          sed -i "s/\"version\": \".*\"/\"version\": \"$FULLTAG\"/" package.json
+          cat package.json | grep '"version"'  # Optional: Verify the change
+          yarn build:win:arm64
+
+      - name: Upload artifacts
+        uses: actions/upload-artifact@v4
+        with:
+          path: ./ui-desktop/dist/morpheus-ui-${{ needs.Generate-Tag.outputs.vfull }}-arm64-win.exe
+          name: morpheus-ui-${{ needs.Generate-Tag.outputs.vfull }}-arm64-win.exe
+          
   UI-Release:
     name: Upload UI-Desktop Release
     if: |
@@ -584,7 +725,9 @@ jobs:
       - UI-macOS-14-arm64
       - UI-macOS-13-x64
       - UI-Ubuntu-22-x64
+      - UI-Ubuntu-22-arm64
       - UI-Windows-avx2-x64
+      - UI-Windows-arm64
     runs-on: ubuntu-latest
     steps:
       - name: Clone
